[package]
name = "miniml"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

build = "build.rs"

[build-dependencies]
lalrpop = "0.10.0"

[dependencies]
lalrpop-util = "0.10.0"
