[package]
name = "miniml"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
syntax = { path = "./syntax" }
syntax_ll = { path = "./syntax_ll" }
ast = { path = "./ast" }
